[package]
name = "minitel-esp"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-hal = "0.44.1"
minitel-stum = { version = "0.1.0", path = "../minitel-stum" }

[lib]
name = "minitel_esp"
harness = false
bench = false
doctest = false
test = false
crate-type = ["lib"]
