[package]
name = "minitel-esp"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-hal = "0.44.1"
minitel-stum = { version = "0.1.0", path = "../minitel-stum" }

[workspace]

#[profile.release]
#opt-level = "s"
#
#[profile.dev]
#debug = true    # Symbols are nice and they don't increase the size on Flash
#opt-level = "z"

[lib]
name = "minitel_esp"
harness = false
bench = false
doctest = false
test = false
crate-type = ["lib"]
