[package]
name = "minitel"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "minitel-ratatui",
    "minitel-stum",
    "minitel-ws",
    "minitel-esp-example",
]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
minitel-stum = { version = "0.1.0", path = "minitel-stum" }
minitel-ws = { version = "0.1.0", path = "minitel-ws", optional = true }
minitel-ratatui = { version = "0.1.0", path = "minitel-ratatui", optional = true }
ratatui = { version = "0.29.0", optional = true }
tungstenite = { version = "0.26.1", optional = true }

[features]
default = []
ws = ["dep:tungstenite", "dep:minitel-ws"]
ratatui = ["dep:ratatui", "dep:minitel-ratatui"]

[dev-dependencies]
env_logger = "0.11.6"
log = "0.4.22"
tungstenite = "0.26.1"
minitel-ws = { version = "0.1.0", path = "minitel-ws" }
minitel = { version = "0.1.0", path = ".", features = ["ws", "ratatui"] }
ratatui = { version = "0.29.0", default-features = false }
