[package]
name = "minitel"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["minitel-ratatui", "minitel-stum", "minitel-ws"]
exclude = ["minitel-esp", "minitel-esp-example"]

[dependencies]
minitel-stum = { version = "0.1.0", path = "minitel-stum" }
minitel-ws = { version = "0.1.0", path = "minitel-ws", optional = true }
minitel-esp = { version = "0.1.0", path = "minitel-esp", optional = true }
minitel-ratatui = { version = "0.1.0", path = "minitel-ratatui", optional = true }
ratatui = { version = "0.29.0", optional = true, default-features = false }
tungstenite = { version = "0.26.1", optional = true, default-features = false }

[features]
default = []
ws = ["dep:tungstenite", "dep:minitel-ws"]
esp = ["dep:minitel-esp"]
ratatui = ["dep:ratatui", "dep:minitel-ratatui"]

[dev-dependencies]
env_logger = "0.11.6"
log = "0.4.22"
tungstenite = "0.26.1"
minitel-ws = { version = "0.1.0", path = "minitel-ws" }
minitel = { version = "0.1.0", path = ".", features = ["ws", "ratatui"] }
ratatui = { version = "0.29.0", default-features = false }
