[package]
name = "minitel"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["minitel-stum", "minitel-ws"]

[dependencies]


[dev-dependencies]
env_logger = "0.11.6"
log = "0.4.22"
tungstenite = "0.26.1"
minitel-ws = { version = "0.1.0", path = "minitel-ws" }
