[build]
#target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash" # Select this runner for espflash v3.x.x
rustflags = [
    "--cfg",
    "espidf_time64",
] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.2"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 
CRATE_CC_NO_DEFAULTS = "1"

# Explicit workspace directory for embuild to find its config even with CARGO_TARGET_DIR set
CARGO_WORKSPACE_DIR = { value = "", relative = true }
ESP_IDF_SDKCONFIG = "minitel-esp-example/sdkconfig.defaults"
